apps/usuarios/urls.py
# Django
from django.urls import path

# Views
from apps.usuarios.views import login_user
from apps.usuarios.views import render_login
from apps.usuarios.views import table
from apps.usuarios.views import logout
from apps.usuarios.views import dashboard
from apps.usuarios.views import fetch_user
from apps.usuarios.views import stock
from apps.usuarios.views import sales
from apps.usuarios.views import purchases
from apps.usuarios.views import products
from apps.usuarios.views import fetch_products
from apps.usuarios.views import staff
from apps.usuarios.views import notifications
from apps.usuarios.views import form
from apps.usuarios.views import fetch_categories_and_providers
from apps.usuarios.views import post_product
from apps.usuarios.views import delete_product
from apps.usuarios.views import fetch_product
from apps.usuarios.views import fetch_product_stock
from apps.usuarios.views import fetch_stock_product
from apps.usuarios.views import fetch_clients
from apps.usuarios.views import fetch_sellers
from apps.usuarios.views import fetch_buyers
from apps.usuarios.views import sell_product
from apps.usuarios.views import fetch_sales
from apps.usuarios.views import fetch_purchases
from apps.usuarios.views import delete_sale
from apps.usuarios.views import delete_purchase
from apps.usuarios.views import fetch_provider
from apps.usuarios.views import buy_product
from apps.usuarios.views import fetch_stock
from apps.usuarios.views import edit_stock
from apps.usuarios.views import fetch_staff
from apps.usuarios.views import post_staff
from apps.usuarios.views import get_staff_user
from apps.usuarios.views import delete_staff
from apps.usuarios.views import fetch_notifications
from apps.usuarios.views import read_all_notifications
from apps.usuarios.views import csv_save_to_disk

from apps.usuarios.views import fetch_area_adminarea

# URLPatterns
app_name='usuarios'
urlpatterns = [
    path('', render_login, name='render_login'),
    path('login/', login_user, name='login'),
    path('get_user/', fetch_user, name='get_user'),
    path('table/', table, name='table'),
    path('form/<slug:type>/', form, name='form'),
    path('dashboard/', dashboard, name='dashboard'),
    path('logout/', logout, name='logout'),
    path('stock/', stock, name='stock'),
    path('sales/', sales, name='sales'),
    path('purchases/', purchases, name='purchases'),
    
    # Products
    path('products/', products, name='products'),
    path('fetch_products/', fetch_products, name='get_products'),
    path('staff/', staff, name='staff'),
    path('notifications/', notifications, name='notifications'),
    path('categories_and_providers/', fetch_categories_and_providers, name='fetch_categories_and_providers'),
    path('post_product/', post_product, name='post_product'),
    path('delete_product/<slug:id>/', delete_product, name='delete_product'),
    path('delete_staff/<slug:id>/', delete_staff, name='delete_staff'),
    path('fetch_product/<slug:id>/', fetch_product, name='fetch_product'),
    path('fetch_product_stock/<slug:id>/', fetch_product_stock, name='fetch_product_stock'),
    path('fetch_provider/<slug:id>/', fetch_provider, name='fetch_provider'),
    path('fetch_clients/', fetch_clients, name='fetch_clients'),
    path('fetch_sellers/', fetch_sellers, name='fetch_sellers'),
    path('fetch_buyers/', fetch_buyers, name='fetch_buyers'),
    path('sell_product/', sell_product, name='sell_product'),
    path('buy_product/', buy_product, name='buy_product'),
    path('fetch_sales/<slug:flag>/', fetch_sales, name='fetch_sales'),
    path('fetch_sales/<slug:flag>/<slug:user>/', fetch_sales, name='fetch_sales1'),
    path('fetch_purchases/<slug:flag>/', fetch_purchases, name='fetch_purchases'),
    path('fetch_purchases/<slug:flag>/<slug:user>/', fetch_purchases, name='fetch_purchases1'),
    path('fetch_stock/', fetch_stock, name='fetch_stock'),
    path('delete_sale/<slug:id>/', delete_sale, name='delete_sale'),
    path('delete_purchase/<slug:id>/', delete_purchase, name='delete_purchase'),
    path('fetch_stock_product/<slug:id>/', fetch_stock_product, name='fetch_stock_product'),
    path('edit_stock/', edit_stock, name='edit_stock'),
    path('fetch_staff/<slug:user>/', fetch_staff, name='fetch_staff'),
    path('post_staff/', post_staff, name='post_staff'),
    path('get_staff_user/<slug:id>/', get_staff_user, name='get_staff_user'),
    path('fetch_notifications/', fetch_notifications, name='fetch_notifications'),
    path('read_all_notifications/<slug:id>/', read_all_notifications, name='read_all_notifications'),
    path('csv_save_to_disk/<slug:type_csv>/', csv_save_to_disk, name='csv_save_to_disk'),
    path('fetch_area_adminarea/', fetch_area_adminarea, name='fetch_area_adminarea'),
]

inventsoft/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.usuarios.urls')),
]

templates/dashboard.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Inventsoft - Dashboard</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <link rel="stylesheet" href="{% static 'css/dashboard.css' %}">
    <link rel="stylesheet" href="{% static 'css/modal.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Sarabun:200,300,400,700,800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
</head>

<body>
    
</body>

<script src="{% static 'js/design_patterns/factoryUserView.js' %}"></script>
<script src="{% static 'js/design_patterns/singletonUser.js' %}"></script>
<script src="{% static 'js/templates/nav.js' %}"></script>
<script src="{% static 'js/templates/dashboard.js' %}"></script>
<script src="{% static 'js/functions.js' %}"></script>
<script src="{% static 'js/styleFunctions.js' %}"></script>

<script>
    (async function(){

    // ------------------------------------------------
        // get user
        const user = await getSingleton();
        
    // ------------------------------------------------
        // Get nav specific options for that user type
        document.body.innerHTML += ViewNav(user);

    // ------------------------------------------------
        // Show notitification count in nav-bar
        showNotificationCount();

    // ------------------------------------------------
        // Get dashboard specific options for that user type
        document.body.innerHTML += ViewDashboard(user);


    })();

</script>

</html>

templates/form.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Inventsoft - Registro</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <link rel="stylesheet" href="{% static 'css/form.css' %}">
    <link rel="stylesheet" href="{% static 'css/modal.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Sarabun:200,300,400,700,800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
</head>

<body>
    {% csrf_token %}
</body>

<script src="{% static 'js/design_patterns/factoryUserView.js' %}"></script>
<script src="{% static 'js/design_patterns/singletonUser.js' %}"></script>
<script src="{% static 'js/templates/nav.js' %}"></script>
<script src="{% static 'js/templates/forms.js' %}"></script>
<script src="{% static 'js/functions.js' %}"></script>
<script src="{% static 'js/styleFunctions.js' %}"></script>
<script src="{% static 'js/cleave.js' %}"></script>
<script src="{% static 'js/templates/form-data/products.js' %}"></script>
<script src="{% static 'js/templates/form-data/purchases.js' %}"></script>
<script src="{% static 'js/templates/form-data/sales.js' %}"></script>
<script src="{% static 'js/templates/form-data/stock.js' %}"></script>
<script src="{% static 'js/templates/form-data/staff-admin.js' %}"></script>
<script src="{% static 'js/templates/form-data/staff.js' %}"></script>

<script>
    (async function(){

    // ------------------------------------------------
        // get user
        const user = await getSingleton();
        
    // ------------------------------------------------
        // Get nav specific options for that user type
        document.body.innerHTML += ViewNav(user);

    // ------------------------------------------------
        // Show notitification count in nav-bar
        showNotificationCount();

    // ------------------------------------------------
        // Get form specific options for that form type
        document.body.innerHTML += factoryFormView(getFormType());

    // ------------------------------------------------
        // Get form specific data for that form type
        factoryFormData(getFormType(), user);
        
    })();

</script>

</html>

templates/home.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Inventsoft - Inicio Sesión</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <link rel="stylesheet" href="{% static 'css/table.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Sarabun:200,300,400,700,800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
</head>
<body>
    <nav class="nav">
        <label>&copy Inventsoft</label>
        <div class="active-user-container">
            <p>Bienvenido, <button id="active-user">Juan López</button></p>
        </div>
        <a href="{% url 'usuarios:logout' %}">LogOut</a>
    </nav>

    <section class="options-container">
        <a href="" class="option">
            <i class="fas fa-laptop"></i>
            <span>Categoría</span>
        </a>

        <a href="" class="option">
            <i class="fas fa-laptop"></i>
            <span>Categoría</span>
        </a>

        <a href="" class="option">
            <i class="fas fa-laptop"></i>
            <span>Categoría</span>
        </a>

        <a href="" class="option">
            <i class="fas fa-laptop"></i>
            <span>Categoría</span>
        </a>

            
    </section>

    <div class="container-fluid main-container">
        <div class="row main-row-container">
            <div class="col-10 result-container">
                <div class="result-title">
                    <i class="fas fa-laptop"></i>
                    <h2>Categoría</h2>
                </div>
                <div class="result-options-container">
                    <button class="result-option btn">Nuevo registro</button>
                </div>
                <div class="table-responsive">
                    <table class="table table-container">
                        <thead>
                            <th scope="col">#</th>
                            <th scope="col">Acciones</th>
                            <th scope="col">Apellido Paterno</th>
                            <th scope="col">Apellido Materno</th>
                            <th scope="col">Nombre</th>
                            <th scope="col">Correo</th>
                        </thead>
                        <tbody>
                            <tr>
                                <th scope="row">1</th>
                                <td class="table-actions">
                                    <a href="">
                                        <i class="fas fa-pen"></i>
                                    </a>
                                    <a href="">
                                        <i class="fas fa-trash"></i>
                                    </a>
                                </td>
                                <td>León</td>
                                <td>Martínez</td>
                                <td>Alejandro</td>
                                <td>alejandro@gmail.com</td>
                            </tr>
    
                            <tr>
                                <th scope="row">2</th>
                                <td class="table-actions">
                                    <a href="">
                                        <i class="fas fa-pen"></i>
                                    </a>
                                    <a href="">
                                        <i class="fas fa-trash"></i>
                                    </a>
                                </td>
                                <td>León</td>
                                <td>Martínez</td>
                                <td>Alejandro</td>
                                <td>alejandro@gmail.com</td>
                            </tr>
    
                            <tr>
                                <th scope="row">3</th>
                                <td class="table-actions">
                                    <a href="">
                                        <i class="fas fa-pen"></i>
                                    </a>
                                    <a href="">
                                        <i class="fas fa-trash"></i>
                                    </a>
                                </td>
                                <td>León</td>
                                <td>Martínez</td>
                                <td>Alejandro</td>
                                <td>alejandro@gmail.com</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

</body>
</html>

templates/login.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Inventsoft - Login</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/form.css' %}">
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    <link rel="stylesheet" href="{% static 'css/modal.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Sarabun:200,300,400,700,800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
</head>
<body>
    <nav class="nav">
        <label>&copy Inventsoft</label>
    </nav>

    <div class="container-fluid main-container">
        <div class="row row-form">
            <div class="col-xl-3 col-lg-3 col-md-4 col-sm-5 col-10 col-form">
                <div class="form-container">
                    <h1>Inventsoft</h1>
                    <h2>Inicio Sesión</h2>
                    <form id="formLogin" action="." method="POST" class="form">
                        {% csrf_token %}
                        <input type="email" id="user" placeholder="Nombre de usuario:" onclick="resetInputError()">
                        <input type="password" name="" id="password" placeholder="Contraseña:" onclick="resetInputError()">
                        <div class="error" id="error"></div>
                        <button type="submit" class="btn btn-submit">Iniciar Sesión</button>
                    </form>
                    <div class="detail">
                        <p>Inventsoft &copy Software Solutions</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
<script src="{% static 'js/design_patterns/singletonUser.js' %}"></script>
<script src="{% static 'js/functions.js' %}"></script>
<script src="{% static 'js/styleFunctions.js' %}"></script>
<script>
    const FORMLOGIN = document.getElementById('formLogin');
    const URL = 'http://127.0.0.1:8000/login/';
    const CSRF_TOKEN = document.getElementsByName('csrfmiddlewaretoken')[0].value;


    FORMLOGIN.addEventListener('submit', async (e) => {
        e.preventDefault();

        if(document.getElementById('user').value != "" && document.getElementById('password').value != ""){
        
            const form = new FormData();
            form.append('username', document.getElementById('user').value);
            form.append('password', document.getElementById('password').value);

            try {
                const data = await mandarData(URL, form);
                if(data.status === 200){
                    showModal('Ingreso exitoso', 'fas fa-check-circle', '/dashboard/');
                } else {
                    document.getElementById('error').innerHTML = `<p>Usuario o contraseña inválidos</p>`;
                }
            } catch (error) {
                console.log(error);
                document.getElementById('error').innerHTML = `<p>Ocurrió un error, intenta de nuevo</p>`;
            }
        }
        else{
            document.getElementById('error').innerHTML = `<p>Uno o más campos vacíos</p>`;
        }
    })
</script>
</html>

templates/notifications.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Inventsoft - Notificaciones</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <link rel="stylesheet" href="{% static 'css/notifications.css' %}">
    <link rel="stylesheet" href="{% static 'css/modal.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Sarabun:200,300,400,700,800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
</head>

<body>
</body>

<script src="{% static 'js/design_patterns/factoryUserView.js' %}"></script>
<script src="{% static 'js/design_patterns/singletonUser.js' %}"></script>
<script src="{% static 'js/templates/nav.js' %}"></script>
<script src="{% static 'js/templates/notifications.js' %}"></script>
<script src="{% static 'js/functions.js' %}"></script>
<script src="{% static 'js/styleFunctions.js' %}"></script>

<script>
    (async function(){

    // ------------------------------------------------
        // get user
        const user = await getSingleton();
        
    // ------------------------------------------------
        // Get nav specific options for that user type
        document.body.innerHTML += ViewNav(user);

    // ------------------------------------------------
        // Show notitification count in nav-bar
        showNotificationCount();
        addNotification();

    // ------------------------------------------------
        // Get notification template
        const notif =  await getNotiData('http://127.0.0.1:8000/fetch_notifications/');
        document.body.innerHTML += ViewNotifications(notif.notifications);

    })();

</script>

</html>

templates/products.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Inventsoft - Productos</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <link rel="stylesheet" href="{% static 'css/table.css' %}">
    <link rel="stylesheet" href="{% static 'css/modal.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Sarabun:200,300,400,700,800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/dom-to-image/2.6.0/dom-to-image.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.5.3/jspdf.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
</head>

<body>

</body>

<script src="{% static 'js/design_patterns/factoryUserView.js' %}"></script>
<script src="{% static 'js/design_patterns/singletonUser.js' %}"></script>
<script src="{% static 'js/templates/nav.js' %}"></script>
<script src="{% static 'js/templates/tables/products.js' %}"></script>
<script src="{% static 'js/templates/rows/products.js' %}"></script>
<script src="{% static 'js/functions.js' %}"></script>
<script src="{% static 'js/styleFunctions.js' %}"></script>

<script>
    (async function(){

        document.body.innerHTML += showOptionModal('¿Eliminar registro?');
        document.body.innerHTML += includeModal();

        localStorage.removeItem('productKey');
    // ------------------------------------------------
        // Get user
        const user = await getSingleton();
        
    // ------------------------------------------------
        // Get nav specific options for that user type
        document.body.innerHTML += ViewNav(user);

    // ------------------------------------------------
        // Show notitification count in nav-bar
        showNotificationCount();

    // ------------------------------------------------
        // Get table data
        async function getProductsData() {
            const response = await fetch('/fetch_products/');
            const data = await response.json();
            return data.products;
        }

        const data = await getProductsData();

        
    // ------------------------------------------------
        // Show table data and specific options for that user type
        document.body.innerHTML += factoryTableViewProducts(user, data);

        const DELETEBUTTONS = document.querySelectorAll('#delete');

        for(let deleteButton of DELETEBUTTONS){
            deleteButton.addEventListener('click', async(e) => {
                e.preventDefault();
                
                changeClass('modal-back-show', 'modal-options');
                
                document.getElementById('ok').onclick = async function(){

                    changeClass('modal-back-show', 'modal-options');
                    
                    const productKey = deleteButton.parentElement.parentElement.firstChild.nextElementSibling.innerText;
                    
                    try{
                        const data = await sendData(`http://127.0.0.1:8000/delete_product/${productKey}/`);
                        if (data.status === 200){
                            deleteButton.parentElement.parentElement.remove();
                            showSuccessModal('Registro eliminado <br> exitosamente', 'fas fa-check-circle');
                        } else {
                            showSuccessModal('Ocurrió un error, <br> intenta de nuevo', 'fas fa-times');
                            
                        }
                    } catch (error) {
                        console.log(error)
                    }
                }
            })
        }

        const EDITBUTTONS = document.querySelectorAll('.edit-row');
        for(let editButton of EDITBUTTONS){
            editButton.addEventListener('click', async(e) => {
                const productKey = editButton.parentElement.parentElement.firstChild.nextElementSibling.innerText;
                console.log(productKey)
                localStorage.setItem('productKey', productKey);
            })
        }


    })();

</script>

</html>

templates/purchases.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Inventsoft - Compras</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <link rel="stylesheet" href="{% static 'css/table.css' %}">
    <link rel="stylesheet" href="{% static 'css/modal.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Sarabun:200,300,400,700,800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/dom-to-image/2.6.0/dom-to-image.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.5.3/jspdf.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
</head>

<body>

</body>

<script src="{% static 'js/design_patterns/factoryUserView.js' %}"></script>
<script src="{% static 'js/design_patterns/singletonUser.js' %}"></script>
<script src="{% static 'js/templates/nav.js' %}"></script>
<script src="{% static 'js/templates/tables/purchases.js' %}"></script>
<script src="{% static 'js/templates/rows/purchases.js' %}"></script>
<script src="{% static 'js/functions.js' %}"></script>
<script src="{% static 'js/styleFunctions.js' %}"></script>

<script>
    (async function(){

        document.body.innerHTML += showOptionModal('¿Eliminar registro?');
        document.body.innerHTML += includeModal();

    // ------------------------------------------------
        // Get user
        const user = await getSingleton();
        
    // ------------------------------------------------
        // Get nav specific options for that user type
        document.body.innerHTML += ViewNav(user);

    // ------------------------------------------------
        // Show notitification count in nav-bar
        showNotificationCount();
        
    // ------------------------------------------------
        // Get table data
        async function getPurchasesData(url) {
            const response = await fetch(url);
            const data = await response.json();
            return data.sales;
        }
        
        let data;
        if(getUserType(user) == 0 || getUserType(user) == 1){
            data = await getPurchasesData('http://127.0.0.1:8000/fetch_purchases/1/');
        } else if(getUserType(user) == 2){
            console.log(user)
            data = await getPurchasesData(`http://127.0.0.1:8000/fetch_purchases/2/${user.emp_key}/`);
        }


    // ------------------------------------------------
        // Show table data and specific options for that user type
        document.body.innerHTML += factoryTableViewPurchases(user, data);

        const DELETEBUTTONS = document.querySelectorAll('#delete');

        for(let deleteButton of DELETEBUTTONS){
            deleteButton.addEventListener('click', async(e) => {
                e.preventDefault();

                changeClass('modal-back-show', 'modal-options');
                
                document.getElementById('ok').onclick = async function(){

                    changeClass('modal-back-show', 'modal-options');
                
                    const purchaseKey = deleteButton.parentElement.parentElement.firstChild.nextElementSibling.innerText;
                    try{
                        const data = await sendData(`http://127.0.0.1:8000/delete_purchase/${purchaseKey}/`);
                        if (data.status === 200){
                            // alert('Se elimino el registro')
                            deleteButton.parentElement.parentElement.remove();
                            showSuccessModal('Registro eliminado <br> exitosamente', 'fas fa-check-circle');
                        } else {
                            showSuccessModal('Ocurrió un error, <br> intenta de nuevo', 'fas fa-times');
                        }
                    } catch (error) {
                        console.log(error)
                    }
                }
            })
        }

    // -----------------------------
        // Get CSV
        getCSV('http://127.0.0.1:8000/csv_save_to_disk/PURCHASES/');

    })();

</script>

</html>